openapi: 3.0.0
info:
  title: RVA Solutions test API
  version: 1.0.0


servers:
  - url: /api

components:
  responses:
    JsonValidationError:
      description: Invalid data
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                example: The given data was invalid
              errors:
                type: object
                properties:
                  field_name:
                    type: array
                    items:
                      type: string
                      example: Attribute field_name is required.

  securitySchemes:
    Bearer:
      type: http
      scheme: bearer

  schemas:
    AuthUser:
      $ref: schemas.yaml#/AuthUser

paths:
  /user/register:
    $ref: data/user.yaml#/~1register
  /user/login:
    $ref: data/user.yaml#/~1login
  /user/info:
    $ref: data/user.yaml#/~1info
  /user/logout:
    $ref: data/user.yaml#/~1logout
